### ISSUE TITLE
permission denied error during Keycloak service building

### ISSUE THREAD

**Issue by Eduvilascoder** [jbossdemocentral/brms-coolstore-demo-angular-patternfly#2]
Trying to run docker's version of this demo I've got permission denied error during the building of Keycloak service. 

Any idea how to solve it? Thanks, Edu.

 ---> c73380e18b2f
Step 2 : MAINTAINER James Falkner jfalkner@redhat.com
 ---> Running in 36f5868b83e5
 ---> f932516f8b73
Removing intermediate container 36f5868b83e5
Step 3 : USER root
 ---> Running in 14051f98f21c
 ---> 652acb6f7b91
Removing intermediate container 14051f98f21c
Step 4 : COPY support/keycloak-config.json support/keycloak-setup.sh /tmp/
 ---> 0a3b367bbac7
Removing intermediate container 5308e1fbdc2c
Step 5 : RUN chmod a+x /tmp/keycloak-setup.sh
 ---> Running in 87234a5db94d
permission denied
ERROR: Service 'keycloak' failed to build: [8] System error: permission denied

**Comment by jamesfalkner** [comment]
Weird.. what version of Docker are you running? Can you try this simple test:

```
docker run docker.io/centos sh -c "touch /tmp/foo; echo x > /tmp/foo; chmod a+x /tmp/foo; cat /tmp/foo ; ls -l /tmp/foo"
```

**Comment by Eduvilascoder** [comment]
Hi James, 
               this my dockerś version:Client:
 Version:         1.9.1
 API version:     1.21
 Package version: docker-1.9.1-9.gitee06d03.fc23.x86_64
 Go version:      go1.5.3
 Git commit:      ee06d03/1.9.1
 Built:           
 OS/Arch:         linux/amd64

Server:
 Version:         1.9.1
 API version:     1.21
 Package version: docker-1.9.1-9.gitee06d03.fc23.x86_64
 Go version:      go1.5.3
 Git commit:      ee06d03/1.9.1
 Built:           
 OS/Arch:         linux/amd64

running the simple test

```
  From: James Falkner <notifications@github.com>
```

 To: jbossdemocentral/brms-coolstore-demo-angular-patternfly brms-coolstore-demo-angular-patternfly@noreply.github.com 
Cc: Eduardo Vilas evilas67@gmail.com; Author author@noreply.github.com
 Sent: Thursday, May 5, 2016 4:10 PM
 Subject: Re: [jbossdemocentral/brms-coolstore-demo-angular-patternfly] permission denied error during Keycloak service building (#2)

Weird.. what version of Docker are you running? Can you try this simple test:docker run docker.io/centos sh -c "touch /tmp/foo; echo x > /tmp/foo; chmod a+x /tmp/foo; cat /tmp/foo ; ls -l /tmp/foo"

**Comment by Eduvilascoder** [comment]
Running the simple test I've got the error
Status: Downloaded newer image for docker.io/centos:latest

permission denied
Error response from daemon: Cannot start container d0311e718818f87b6bc87c4948dd5c6ed0ad1fb600ae633da084c3481538a763: [8] System error: permission denied
running with --privileged works ok.
Coolstore demo use docker-composite build so I don't know how to add --privileged tag.

```
  From: James Falkner <notifications@github.com>
```

 To: jbossdemocentral/brms-coolstore-demo-angular-patternfly brms-coolstore-demo-angular-patternfly@noreply.github.com 
Cc: Eduardo Vilas evilas67@gmail.com; Author author@noreply.github.com
 Sent: Thursday, May 5, 2016 4:10 PM
 Subject: Re: [jbossdemocentral/brms-coolstore-demo-angular-patternfly] permission denied error during Keycloak service building (#2)

Weird.. what version of Docker are you running? Can you try this simple test:docker run docker.io/centos sh -c "touch /tmp/foo; echo x > /tmp/foo; chmod a+x /tmp/foo; cat /tmp/foo ; ls -l /tmp/foo"

**Comment by jamesfalkner** [comment]
Edit the `docker-compose.yml` file that you copied into the root directory of the project and add `privileged: true` to each of the two services. For example:

```
keycloak:
        build: .
        dockerfile: Dockerfile.keycloak
        hostname: keycloak
        privileged: true
        expose:
                - 8080
        ports:
                - "8181:8080"

coolstore:
        build: .
        dockerfile: Dockerfile.coolstore
        hostname: coolstore
        privileged: true
        expose:
                - 9990
                - 9999
                - 8080
        ports:
                - "8080:8080"
                - "9999:9999"
                - "9990:9990"
        links:
                - keycloak
```
